/* USERS */
export const GET_COMPANIES_OPTIONS = "GET_COMPANIES_OPTIONS";
export const GET_COMPANIES_OPTIONS_SUCCESS = "GET_COMPANIES_OPTIONS_SUCCESS";
export const GET_COMPANIES_OPTIONS_FAIL = "GET_COMPANIES_OPTIONS_FAIL";

export const GET_COMPANIES_MASTER_OPTIONS = "GET_COMPANIES_OPTIONS";
export const GET_COMPANIES_MASTER_OPTIONS_SUCCESS = "GET_COMPANIES_MASTER_OPTIONS_SUCCESS";
export const GET_COMPANIES_MASTER_OPTIONS_FAIL = "GET_COMPANIES_MASTER_OPTIONS_FAIL";
 export const SAVE_SELECTED_COMPANY="SAVE_SELECTED_COMPNAY";
 export const SAVE_SELECTED_COMPANY_SUCCESS="SAVE_SELECTED_COMPANY";
 export const SAVE_SELECTED_COMPANY_FAIL="SAVE_SELECTED_COMPANY";
 