export const GET_WASTEITEMS="GET_WASTEITEMS";
export const GET_WASTEITEMS_SUCCESS="GET_WASTEITEMS_SUCCESS";
export const GET_WASTEITEMS_FAIL="GET_WASTEITEMS_FAIL";

export const GET_WASTE_TYPES="GET_WASTE_TYPES";
export const GET_WASTE_TYPES_SUCCESS="GET_WASTE_TYPES_SUCCESS";
export const GET_WASTE_TYPES_FAIL="GET_WASTE_TYPES_FAIL";

export const GET_WASTE_CATEGORIES="GET_WASTE_CATEGORIES";
export const GET_WASTE_CATEGORIES_SUCCESS="GET_WASTE_CATEGORIES_SUCCESS";
export const GET_WASTE_CATEGORIES_FAIL="GET_WASTE_CATEGORIES_FAIL";


